"use client";

// ** Import 3rd Party Libs
import { ColumnDef } from "@tanstack/react-table";

// ** Import Components
import { DataTableColumnHeader } from "@/components/data-table/column-header";

// ** Import UI Components
import { Checkbox } from "@/components/ui/checkbox";
import { Button } from "@/components/ui/button";

// ** Import Schema

// ** Import Table Row Actions
import { cn } from "@/lib/utils";
import { PayslipData } from "../data";

export const getColumns = (
  handleRowDeselection: ((rowId: string) => void) | null | undefined
): ColumnDef<PayslipData>[] => {
  // Base columns without the select column
  const baseColumns: ColumnDef<PayslipData>[] = [
    {
      accessorKey: "payslip_id",
      header: ({ column }) => (
        <DataTableColumnHeader column={column} title="Payslip ID" />
      ),
      cell: ({ row }) => (
        <div className="font-medium text-left">
          {row.getValue("payslip_id")}
        </div>
      ),
      size: 120,
    },
    {
      accessorKey: "month_year",
      header: ({ column }) => (
        <DataTableColumnHeader column={column} title="Month/Year" />
      ),
      cell: ({ row }) => (
        <div className="truncate text-left">{row.getValue("month_year")}</div>
      ),
      size: 120,
    },
    {
      accessorKey: "generated_date",
      header: ({ column }) => (
        <DataTableColumnHeader column={column} title="Generated Date" />
      ),
      cell: ({ row }) => (
        <div className="truncate text-left">
          {row.getValue("generated_date")}
        </div>
      ),
      size: 150,
    },
    {
      accessorKey: "generated_type",
      header: ({ column }) => (
        <DataTableColumnHeader column={column} title="Generated Type" />
      ),
      cell: ({ row }) => {
        const generatedType = row.getValue("generated_type") as string;
        const badgeColor =
          generatedType === "Auto"
            ? "bg-status-absent-sl/20 text-status-absent-sl" 
            : generatedType === "Manual"
            ? "bg-status-inactive/20 text-status-inactive" 
            : "bg-primary/20 text-primary"; 

        return (
          <div className={cn("px-2 py-1.5 text-center rounded-full ", badgeColor)}>
            {generatedType}
          </div>
        );
      },
      size: 150,
    },
    {
      accessorKey: "generated_by",
      header: ({ column }) => (
        <DataTableColumnHeader column={column} title="Generated By" />
      ),
      cell: ({ row }) => (
        <div className="truncate text-left">{row.getValue("generated_by")}</div>
      ),
      size: 180,
    },
    {
      id: "payslip",
      header: ({ column }) => (
        <DataTableColumnHeader column={column} title="Payslip" />
      ),
      cell: () => {
        return (
          <Button
            size="sm"
            className="bg-primary text-primary-foreground px-5 font-semibold"
          >
            View
          </Button>
        );
      },
      size: 120,
    },
    {
      accessorKey: "status",
      header: ({ column }) => (
        <DataTableColumnHeader column={column} title="Status" />
      ),
      cell: ({ row }) => {
        const status = row.getValue("status") as string;
        const badgeColor =
          status === "Sent"
            ? "bg-status-active text-white"
            : status === "Pending"
            ? "bg-status-inactive text-black"
            : "bg-primary text-white"; // Default color for other statuses
        return (
          <Button size="sm" className={cn(" px-5 font-semibold", badgeColor)}>
            {status}
          </Button>
        );
      },
      size: 180,
    },
    
  ];

  // Only include the select column if row selection is enabled
  if (handleRowDeselection !== null) {
    return [
      {
        id: "select",
        header: ({ table }) => (
          <div className="pl-2 truncate">
            <Checkbox
              checked={
                table.getIsAllPageRowsSelected() ||
                (table.getIsSomePageRowsSelected() && "indeterminate")
              }
              onCheckedChange={(value) =>
                table.toggleAllPageRowsSelected(!!value)
              }
              aria-label="Select all"
              className="translate-y-0.5 cursor-pointer"
            />
          </div>
        ),
        cell: ({ row }) => (
          <div className="truncate">
            <Checkbox
              checked={row.getIsSelected()}
              onCheckedChange={(value) => {
                if (value) {
                  row.toggleSelected(true);
                } else {
                  row.toggleSelected(false);
                  // If we have a deselection handler, use it for better cross-page tracking
                  if (handleRowDeselection) {
                    handleRowDeselection(row.id);
                  }
                }
              }}
              aria-label="Select row"
              className="translate-y-0.5 cursor-pointer"
            />
          </div>
        ),
        enableSorting: false,
        enableHiding: false,
        size: 50,
      },
      ...baseColumns,
    ];
  }

  // Return only the base columns if row selection is disabled
  return baseColumns;
};
