import { useMemo } from "react";

/**
 * Default export configuration for the salary details data table
 */
export function useExportConfig() {
  // Column mapping for export
  const columnMapping = useMemo(() => {
    return {
      id: "ID",
      payslip_id: "Payslip ID",
      month_year: "Month/Year",
      generated_date: "Generated Date",
      generated_type: "Generated Type",
      generated_by: "Generated By",
      status: "Status",
    };
  }, []);

  // Column widths for Excel export
  const columnWidths = useMemo(() => {
    return [
      { wch: 10 }, // ID
      { wch: 15 }, // Payslip ID
      { wch: 15 }, // Month/Year
      { wch: 20 }, // Generated Date
      { wch: 15 }, // Generated Type
      { wch: 25 }, // Generated By
      { wch: 15 }, // Status
    ];
  }, []);

  // Headers for CSV export
  const headers = useMemo(() => {
    return [
      "id",
      "payslip_id",
      "month_year",
      "generated_date",
      "generated_type",
      "generated_by",
      "status",
    ];
  }, []);

  return {
    columnMapping,
    columnWidths,
    headers,
    entityName: "by id",
  };
}
